// This code is part of the Sakura framework project. Licensed under the MIT License.
// See the LICENSE file for full license text.

namespace Sakura.Framework.Allocation;

/// <summary>
/// Implemented by the source generator on every <see cref="IDependencyInjectionCandidate"/> class.
/// Calling <see cref="RegisterForDependencyActivation"/> walks the full inheritance chain once and
/// registers compile-time inject/cache delegates into the <see cref="DependencyActivator"/> cache,
/// so subsequent activations require no reflection.
/// </summary>
public interface ISourceGeneratedDependencyActivator
{
    /// <summary>
    /// Registers inject and cache delegates for this type (and all base types in the candidate hierarchy)
    /// into the provided <paramref name="registry"/>.
    /// <remarks>This method is generated by the Sakura source generator, do not implement manually.</remarks>
    /// </summary>
    void RegisterForDependencyActivation(IDependencyActivatorRegistry registry);
}
